In [4]:
import pandas as pd
import numpy as np

In [5]:
import ssl
ssl._create_default_https_context=ssl._create_unverified_context

In [9]:
pgh_death_data = pd.read_csv("https://data.wprdc.org/dataset/ee735209-4de7-4ea4-b446-bf0f0f6d9cb3/resource/c2e1500a-a12a-4e91-be94-76c6a892b7e2/download/nhoodmedianage20112015.csv")

pgh_death_data.head()

,NEIGHBORHOOD,BLACKdeaths,Black MD AGE AT DEATH,WHITEdeaths,White MD AGE AT DEATH,TOTALdeaths*,TOTAL MD AGE AT DEATH
0,SOUTH SHORE,0.0,0.0,0.0,0.0,0.0,0.0
1,CHATEAU,0.0,0.0,2.0,NaN,2.0,NaN
2,NORTH SHORE,0.0,0.0,4.0,NaN,5.0,80.0
3,ALLEGHENY WEST,3.0,NaN,4.0,NaN,8.0,65.0
4,SAINT CLAIR,5.0,67.5,5.0,67.5,10.0,67.5

In [19]:
pgh_death_data.sort_values("TOTAL MD AGE AT DEATH")

,NEIGHBORHOOD,BLACKdeaths,Black MD AGE AT DEATH,WHITEdeaths,White MD AGE AT DEATH,TOTALdeaths*,TOTAL MD AGE AT DEATH
0,SOUTH SHORE,0.0,0.0,0.0,0.0,0.0,0.0
9,FAIRYWOOD,11.0,62.5,9.0,42.5,21.0,53.3
7,ARLINGTON HEIGHTS,10.0,55.0,7.0,72.5,17.0,63.7
3,ALLEGHENY WEST,3.0,NaN,4.0,NaN,8.0,65.0
49,EAST ALLEGHENY,51.0,62.7,100.0,70.0,157.0,66.2
42,ALLENTOWN,41.0,55.6,82.0,72.1,126.0,66.5
38,MANCHESTER,97.0,67.2,15.0,70.0,113.0,67.4
4,SAINT CLAIR,5.0,67.5,5.0,67.5,10.0,67.5
22,NORTHVIEW HEIGHTS,51.0,69.5,1.0,NaN,54.0,68.0
14,CALIFORNIA-KIRKBRIDE,16.0,70.0,10.0,70.0,30.0,69.3
17,BLUFF,18.0,71.7,24.0,69.0,42.0,70.0
70,MARSHALL-SHADELAND,55.0,60.0,191.0,73.2,252.0,70.0
48,TROY HILL/HERR'S ISLAND,15.0,42.5,134.0,73.8,151.0,70.3
23,FINEVIEW,19.0,73.3,38.0,70.0,58.0,70.8
54,EAST HILLS,171.0,71.7,4.0,NaN,177.0,70.9
16,FRIENDSHIP,15.0,66.2,24.0,73.0,41.0,71.1
35,TERRACE VILLAGE,94.0,71.8,3.0,NaN,99.0,71.2
32,BEDFORD DWELLINGS,82.0,71.3,5.0,70.0,88.0,71.4
47,CENTRAL NORTHSIDE,90.0,72.0,54.0,73.3,147.0,71.7
6,ESPLEN,3.0,NaN,13.0,72.5,16.0,71.7
58,KNOXVILLE,61.0,61.8,121.0,75.6,188.0,71.7
26,SPRING GARDEN,4.0,NaN,61.0,73.5,67.0,71.8
40,ELLIOTT,28.0,67.0,91.0,73.7,121.0,72.0
69,SHERADEN,62.0,62.2,180.0,76.8,248.0,72.0
73,HAZELWOOD,74.0,68.2,184.0,74.2,261.0,72.2
30,POLISH HILL,9.0,67.5,76.0,72.8,85.0,72.2
55,MIDDLE HILL,174.0,73.1,6.0,61.7,183.0,72.4
8,STRIP DISTRICT,7.0,76.7,12.0,70.0,19.0,72.5
80,EAST LIBERTY,259.0,71.8,91.0,78.4,364.0,73.0
31,POINT BREEZE NORTH,67.0,74.6,18.0,71.0,87.0,73.2
...,...,...,...,...,...,...,...
81,LINCOLN-LEMINGTON-BELMAR,287.0,76.7,98.0,84.7,389.0,78.8
84,BEECHVIEW,35.0,55.8,398.0,80.2,434.0,78.9
86,BRIGHTON HEIGHTS,56.0,63.7,432.0,80.3,496.0,78.9
78,GREENFIELD,8.0,65.0,325.0,79.6,337.0,79.2
45,DUQUESNE HEIGHTS,3.0,NaN,131.0,79.3,134.0,79.2
65,HIGHLAND PARK,49.0,68.7,159.0,83.2,213.0,79.2
21,RIDGEMONT,0.0,0.0,52.0,79.3,52.0,79.3
33,WEST OAKLAND,59.0,73.8,32.0,87.0,93.0,79.5
43,GLEN HAZEL,60.0,80.7,69.0,78.7,131.0,79.8
66,LINCOLN PLACE,3.0,NaN,212.0,80.3,217.0,79.8
2,NORTH SHORE,0.0,0.0,4.0,NaN,5.0,80.0
12,EAST CARNEGIE,9.0,72.5,18.0,81.0,27.0,80.0
25,HOMEWOOD WEST,63.0,80.9,1.0,NaN,66.0,80.3
75,STANTON HEIGHTS,112.0,75.6,165.0,84.0,278.0,80.5
79,CENTRAL LAWRENCEVILLE,18.0,75.0,338.0,81.7,358.0,81.3
18,ALLEGHENY CENTER,21.0,63.3,23.0,86.2,46.0,81.7
60,UPPER HILL,102.0,77.4,88.0,88.4,191.0,81.7
83,SHADYSIDE,72.0,81.2,320.0,82.4,406.0,82.1
77,OVERBROOK,4.0,NaN,284.0,82.5,289.0,82.2
27,SWISSHELM PARK,0.0,0.0,67.0,83.1,67.0,83.1
28,NEW HOMESTEAD,4.0,NaN,67.0,83.8,71.0,83.4
20,CENTRAL OAKLAND,2.0,NaN,50.0,84.0,52.0,84.0
68,SQUIRREL HILL NORTH,6.0,75.0,231.0,85.3,242.0,85.0
53,POINT BREEZE,13.0,66.7,158.0,85.7,175.0,85.1
71,BANKSVILLE,4.0,NaN,247.0,85.5,253.0,85.5
76,NORTH OAKLAND,45.0,70.9,227.0,86.8,279.0,85.6
89,SQUIRREL HILL SOUTH,58.0,83.2,721.0,86.2,802.0,85.9
1,CHATEAU,0.0,0.0,2.0,NaN,2.0,NaN
90,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,*Total includes Other and Unknown race.,NaN,NaN,NaN,NaN,NaN,NaN